name: E2E in custom container
on: 
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    # Cypress Docker image with Chrome v78
    # and Firefox v70 pre-installed
    container: cypress/browsers:node12.13.0-chrome78-ff70
    steps:
      - uses: actions/checkout@v2
      - name: commit
        run: |
          git commit -m "trigger" --allow-empty
          git push origin master
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
